version: '3.9'

services:

  postgres:
    image: postgres:latest
    container_name: pos_container
    volumes:
      - ./postgres_db_pos:/data/db
    restart: always
    ports:
      - "5432:5432"

  api:
    build: .
    container_name: graph_container
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    restart: always
volumes:
  postgres: {}
